import { Header } from "@/components/header/Header";
import { NavSection } from "@/components/navSection/NavSection";
import { ILink } from "@/model/ILink";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lessons: ILink[] = [
  { title: "Lesson 01", path: "/lesson01" },
  { title: "Lesson 02", path: "/lesson02" },
  { title: "Lesson 03", path: "/lesson03" },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <NavSection links={lessons}>{children}</NavSection>
      </body>
    </html>
  );
}
